### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by achille-roussel** [go-playground/backoff#1]
I've been reviewing the code as you requested, here are some feedback:

- https://github.com/go-playground/backoff/blob/master/backoff.go#L115
How did you come up with the factor computation?
How about just making it configurable?
In practice "2" is used very often, so the delay doubles every attempt.

- https://github.com/go-playground/backoff/blob/master/backoff.go#L99
The backoff strategy doesn't add any jitter, if you take a look at https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ they demonstrate how adding randomness to the backoff decreases time-to-success as well as the number of retries needed to complete the operation.

- https://github.com/go-playground/backoff/blob/master/backoff.go#L13
Taking a dependency just for this one line of code seems a bit overkill.

In my experience, backoff management is often very dependent on the program, for example we have cases where we need to store the backoff state machine in a database to survive restarts of the service. In this case this package wouldn't help. Exposing more primitives that allow programs to build and manage their own backoffs could be helpful (for example, functions to compute the next retry times with various strategies).

**Comment by deankarn** [comment]
@achille-roussel Thanks for the feedback 👍 

> https://github.com/go-playground/backoff/blob/master/backoff.go#L115
How did you come up with the factor computation?
How about just making it configurable?
In practice "2" is used very often, so the delay doubles every attempt.

I just reverse engineered the math, if we know the min, max  backoff delays and max attempts:
```
min * factor^max-attempts = max
factor^max-attempts = max/min
factor = max-attempts sqrt(max/min)
factor = max/min * 1/max-attempts
```
The reason I calculate it automatically is an attempt to make an easier to use backoff library; most things I need a backoff for have a maximum delay I want to have, the minimum delay and how many times I want to retry and so hopefully will increase a programmers velocity as they don't have to think about the underlying details as it will handle ensuring the max delay is adhered to( I know you could just use `math.Max` but even distributing the backoff seemed better )


> https://github.com/go-playground/backoff/blob/master/backoff.go#L99
The backoff strategy doesn't add any jitter, if you take a look at https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ they demonstrate how adding randomness to the backoff decreases time-to-success as well as the number of retries needed to complete the operation.

If the [AutoTune](https://github.com/go-playground/backoff/blob/master/backoff.go#L53) feature is used, it will keep track of the number of [backoffs](https://github.com/go-playground/backoff/blob/master/backoff.go#L102) have been performed and after the timeout set in the AutoTune is triggered, it will adjust the minimum wait time and recalculate the factor; my thoughts are that each service will have handled a different number of requests/backoffs due to latency, throughput, etc.. and so when each service recalculates the min and factor it will end up being different, which I was thinking of as a natural jitter. Because AutoTune also has a reset timeout, services will also adjusted to changing conditions.

Do you think it would make sense to also add a jitter into the equation?


> https://github.com/go-playground/backoff/blob/master/backoff.go#L13
Taking a dependency just for this one line of code seems a bit overkill.

Ya I'll probably remove that, was an excuse to use the new `alias` feature ;)


> In my experience, backoff management is often very dependent on the program, for example we have cases where we need to store the backoff state machine in a database to survive restarts of the service. In this case this package wouldn't help. Exposing more primitives that allow programs to build and manage their own backoffs could be helpful (for example, functions to compute the next retry times with various strategies).

I'd definitely like to know more about the how and why of storing the backoff state machine in a database.

That's a great idea on exposing primitives given a particular strategy, I'll look into that.

Again thanks for you feedback 😄
